import Foundation
import CoreML

/// Pinned GMNet PyTorch FP32 references, generated by Scripts/Models/calibrate_gain.py.
/// A shape check or a broad brightness interval alone misses accelerator drift.
enum GainModelCalibration {
    enum Profile { case realWorld, camera }
    static let cameraCheckpoint = "cc92ee36615c30e4b076215e6bffaba551e3b6351f86174aed8da1e5ed3bcf41"
    static func profile(_ model: MLModel) throws -> Profile {
        let metadata = model.modelDescription.metadata[.creatorDefinedKey] as? [String:String] ?? [:]
        if metadata["checkpointSHA256"] == cameraCheckpoint { return .camera }
        if metadata["checkpointSHA256"] == nil,
           metadata["source"] == "qtlark/GMNet@59db6aac16f8fa7071a9447e357d9e7316ce0f8c" { return .realWorld }
        throw EditorFailure.gainModelValidation
    }
    static func sideLength(_ model: MLModel) throws -> Int {
        let shape = model.modelDescription.inputDescriptionsByName["image"]?.multiArrayConstraint?.shape.map(\.intValue)
        guard let shape, shape.count == 4, shape[0] == 1, shape[1] == 3,
              shape[2] == shape[3], [512,1024].contains(shape[2]) else { throw EditorFailure.gainModelValidation }
        return shape[2]
    }

    static func input(size: Int, pattern: Int) throws -> MLDictionaryFeatureProvider {
        func tensor(_ side: Int) throws -> MLMultiArray {
            let array = try MLMultiArray(shape: [1,3,NSNumber(value: side),NSNumber(value: side)], dataType: .float32)
            let pointer = array.dataPointer.bindMemory(to: Float.self, capacity: array.count)
            for c in 0..<3 { for y in 0..<side {
                if y % 32 == 0 { try Task.checkCancellation() }
                for x in 0..<side {
                    pointer[c*side*side+y*side+x] = pattern == 0 ? 0.5 :
                        Float((x*(c+1)+y*(3-c)) % side)/Float(side-1)
                }
            } }
            return array
        }
        return try MLDictionaryFeatureProvider(dictionary: ["image": MLFeatureValue(multiArray: tensor(size)),
                                                            "thumbnail": MLFeatureValue(multiArray: tensor(256))])
    }

    static func reference(size: Int, pattern: Int, profile: Profile = .camera) -> [Float] {
        if profile == .camera {
            if pattern == 0 { return Array(repeating: 0.95621628, count: 9) }
            if size == 1024 { return [1.07285106,1.47899139,1.05952001,1.39748597,0.40715238,0.87229818,0.95205444,0.99886221,1.07285106] }
            return [1.05305648,1.46816719,1.07347655,1.39259827,0.41140857,0.87882417,0.94664741,1.00007284,1.05305648]
        }
        if pattern == 0 { return Array(repeating: 0.35404578, count: 9) }
        if size == 1024 { return [0.39300814,0.68871611,0.37554505,0.64250052,0.26524165,0.60801625,0.44208777,0.63470793,0.39300814] }
        return [0.37860453,0.67198044,0.37464663,0.62857538,0.24883872,0.61282182,0.43885449,0.63195485,0.37860453]
    }

    static func accepts(_ output: MLMultiArray, size: Int, pattern: Int, profile: Profile = .camera) -> Bool {
        guard output.shape.map(\.intValue) == [1,1,size,size] else { return false }
        let positions = [size/8,size/2,size*7/8]
        let samples = positions.flatMap { y in positions.map { x in output[[0,0,NSNumber(value:y),NSNumber(value:x)]].floatValue } }
        let tolerance: Float = pattern == 0 ? 0.02 : 0.04
        return zip(samples, reference(size:size,pattern:pattern,profile:profile)).allSatisfy { $0.isFinite && abs($0-$1) <= tolerance }
    }
}
