import Foundation
import CoreML

/// Pinned GMNet PyTorch FP32 references, generated by Scripts/Models/calibrate_gain.py.
/// A shape check or a broad brightness interval alone misses accelerator drift.
enum GainModelCalibration {
    static func sideLength(_ model: MLModel) throws -> Int {
        let shape = model.modelDescription.inputDescriptionsByName["image"]?.multiArrayConstraint?.shape.map(\.intValue)
        guard let shape, shape.count == 4, shape[0] == 1, shape[1] == 3,
              shape[2] == shape[3], [512,1024].contains(shape[2]) else { throw EditorFailure.gainModelValidation }
        return shape[2]
    }

    static func input(size: Int, pattern: Int) throws -> MLDictionaryFeatureProvider {
        func tensor(_ side: Int) throws -> MLMultiArray {
            let array = try MLMultiArray(shape: [1,3,NSNumber(value: side),NSNumber(value: side)], dataType: .float32)
            let pointer = array.dataPointer.bindMemory(to: Float.self, capacity: array.count)
            for c in 0..<3 { for y in 0..<side {
                if y % 32 == 0 { try Task.checkCancellation() }
                for x in 0..<side {
                    pointer[c*side*side+y*side+x] = pattern == 0 ? 0.5 :
                        Float((x*(c+1)+y*(3-c)) % side)/Float(side-1)
                }
            } }
            return array
        }
        return try MLDictionaryFeatureProvider(dictionary: ["image": MLFeatureValue(multiArray: tensor(size)),
                                                            "thumbnail": MLFeatureValue(multiArray: tensor(256))])
    }

    static func reference(size: Int, pattern: Int) -> [Float] {
        if pattern == 0 { return Array(repeating: 0.35404578, count: 9) }
        if size == 1024 { return [0.39300814,0.68871611,0.37554505,0.64250052,0.26524165,0.60801625,0.44208777,0.63470793,0.39300814] }
        return [0.37860453,0.67198044,0.37464663,0.62857538,0.24883872,0.61282182,0.43885449,0.63195485,0.37860453]
    }

    static func accepts(_ output: MLMultiArray, size: Int, pattern: Int) -> Bool {
        guard output.shape.map(\.intValue) == [1,1,size,size] else { return false }
        let positions = [size/8,size/2,size*7/8]
        let samples = positions.flatMap { y in positions.map { x in output[[0,0,NSNumber(value:y),NSNumber(value:x)]].floatValue } }
        let tolerance: Float = pattern == 0 ? 0.02 : 0.04
        return zip(samples, reference(size:size,pattern:pattern)).allSatisfy { $0.isFinite && abs($0-$1) <= tolerance }
    }
}
